-- Fix profile.id to be a proper unique identifier instead of integer default 1
-- This allows multiple users to each have their own profile row
ALTER TABLE profile ALTER COLUMN id DROP DEFAULT;
ALTER TABLE profile ALTER COLUMN id SET DATA TYPE bigint;
ALTER TABLE profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
